config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    collection do
      match 'setup_totp' => 'users', via: [:get, :post]
      match 'totp_recovery_code' => 'users', via: [:get, :post]
      get 'new_recory_code'
    end
  end

  resources :sessions do
    collection do
      match 'verify_totp_code' => 'sessions', via: [:get, :post]
    end
  end

  resources :password_resets
  resources :dashboard, only: [:index]

  namespace :common_user do
    match 'change_password' => 'abilities#change_password', as: 'change_password', via: [:get, :patch]
    match 'security_settings' => 'abilities#security_settings', as: 'security_settings', via: [:get, :post]
    match 'my_profile' => 'abilities#my_profile', as: 'my_profile', via: [:get, :patch]
  end
  
  namespace :admin do
    resources :users
    resources :bank_accounts do
      get 'recalculate_balance'
    end
    resources :transactions
    resources :transaction_categories
    resources :reports do
      collection do
        get 'filter_report'
        get 'individual_bank_account'
        get ':bank_account/generate_report', action: 'generate_report'
      end
    end
  end

  root to: 'sessions#new'

  match "*path", :to => "application#render_404", via: :all   # renders 404 page when routes not found
  
end

app/views/partials/_dashboard_nav.html.erb
<nav class="sidebar">
  <ul class="nav">
    <li class="nav-item" id="dashboard">
      <%= link_to "Dashboard", dashboard_index_path, class: 'nav-link pad-l25' %>
    </li>

    <li class="nav-item" id="abilities_change_password">
      <%= link_to "Change Password", common_user_change_password_path, class: 'nav-link pad-l25' %>
    </li>
    <li class="nav-item" id="abilities_my_profile">
      <%= link_to "My Profile", common_user_my_profile_path, class: 'nav-link pad-l25' %>
    </li>
    <li class="nav-item" id="abilities_security_settings">
      <%= link_to "Security Settings", common_user_security_settings_path, class: 'nav-link pad-l25' %>
    </li>

    <% if current_user.is_admin? %>
      <li class="nav-item" id="bank_accounts">
        <%= link_to "Bank Accounts", admin_bank_accounts_path, class: 'nav-link pad-l25' %>
      </li>
      <li class="nav-item" id="transactions">
        <%= link_to "Transactions", admin_transactions_path, class: 'nav-link pad-l25' %>
      </li>
      <li class="nav-item" id="users">
        <%= link_to "User Accounts", admin_users_path, class: 'nav-link pad-l25' %>
      </li>
      <li class="nav-item" id="transaction_categories">
        <%= link_to "Transaction Categories", admin_transaction_categories_path, class: 'nav-link pad-l25' %>
      </li>
      <li class="dropdown open" id="reports">
          <a class="dropdown-toggle pad-l25" data-toggle="dropdown" href="#">Generate Report
          <span class="caret pull-right" id="nav-caret"></span></a>
          <ul class="custom-dropdown-menu dropdown-menu">
            <li><%= link_to "Statement", "/admin/reports?type=statement", class: 'nav-link pad-l25', id: 'statement' %></li>
            <li><%= link_to "Report", "/admin/reports?type=report", class: 'nav-link pad-l25', id: 'report' %></li>
          </ul>
        </li>
      </li>
    <% end %>
  </ul>
</nav>

app/views/partials/_form_errors.html.erb
<% if data.errors.any? %>
  <div class="alert alert-danger alert-dismissable" role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <h3 class="prohibited"><%= pluralize(data.errors.count, "error") %> prohibited this user from being saved:</h3>
    <ul class="error_list">
      <% data.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_notifications.html.erb
<!-- Flash Notifications -->
<% flash.each do |name, msg| %>
  <%= content_tag :div, class: "alert alert-#{ name == 'notice' ? "success" : "danger" } alert-dismissable", role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= msg %>
  <% end %>
<% end %>

app/views/partials/_submit_code.html.erb
<%= form_tag(post_url) do %>
  <div class="input-group">
    <% if params[:use_backup_code] == '1' %>
      <%= text_field_tag :backup_code, nil, class: 'form-control pad10', placeholder: 'Enter back up code here:', autofocus: true, required: true %>
    <% else %>
      <%= text_field_tag :code, nil, class: 'form-control pad10', placeholder: 'Enter 6 digit pin code here:', autofocus: true, required: true, maxlength: 6 %>
    <% end %>

    <span class="input-group-btn">
      <%= submit_tag 'Submit', class: 'btn btn-lg btn-primary submit_qrcode' %>
    </span>
  </div>
<% end %>

<br>

<% if params[:use_backup_code] == '1' %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Able To Access Your 2nd Factor Device?</h3>
      <br>
      <%= link_to "Login using 6 Digit code?", verify_totp_code_sessions_url %>
    </div>
  </div>
<% else %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Can't Access Your 2nd Factor Device?</h3>
      <br>
      <a href="<%= request.url%>?use_backup_code=1">Login using Backup Code</a>
    </div>
  </div>
<% end %>