config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    collection do
      match 'setup_totp' => 'users', via: [:get, :post]
      match 'totp_recovery_code' => 'users', via: [:get, :post]
      get 'new_recory_code'
    end
  end

  resources :sessions do
    collection do
      match 'verify_totp_code' => 'sessions', via: [:get, :post]
    end
  end

  resources :password_resets
  resources :dashboard, only: [:index]

  namespace :common_user do
    match 'change_password' => 'abilities#change_password', as: 'change_password', via: [:get, :patch]
    match 'security_settings' => 'abilities#security_settings', as: 'security_settings', via: [:get, :post]
    match 'my_profile' => 'abilities#my_profile', as: 'my_profile', via: [:get, :patch]
  end
  
  namespace :admin do
    resources :users
    resources :bank_accounts do
      get 'recalculate_balance'
    end
    resources :transactions
    resources :transaction_categories
    resources :reports do
      collection do
        get 'filter_report'
        get 'individual_bank_account'
        get ':bank_account/generate_report', action: 'generate_report'
      end
    end
  end

  root to: 'sessions#new'

  match "*path", :to => "application#render_404", via: :all   # renders 404 page when routes not found
  
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user, optional: true
  has_many :bank_transactions, class_name: "Transaction", foreign_key: "account_id", dependent: :destroy

  validates_presence_of :user_id, :description, :bank, :bank_type, :opening_balance, :balance
  # validates_numericality_of :opening_balance, :greater_than => 0, only_integer: false
  # validates :opening_balance, presence: true, numericality: { greater_than: 0, only_integer: false }
  validates_uniqueness_of :account_number unless Rails.env.test?
  validates_length_of :account_number, :within => 8..10, message: "format is invalid", allow_blank: true

  before_validation do
    self.opening_balance = opening_balance.to_s.gsub(",", "").to_f unless opening_balance.blank?
    self.balance = balance.to_s.gsub(",", "").to_f unless balance.blank?
  end

  def recalculate_balance
    # Formula: new_balance = opening_balance + (credits - debits)
    new_balance = (self.opening_balance + self.bank_transactions.get_total_credit.sum(:amount)) - self.bank_transactions.get_total_debit.sum(:amount)
    self.update_attribute(:balance, new_balance)

    return new_balance
  end
end

app/controllers/admin/bank_accounts_controller.rb
class Admin::BankAccountsController < ApplicationController
  before_action :require_login, :allow_admins_only
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'
  include ActionView::Helpers::NumberHelper
  include ApplicationHelper

  # GET /admin/bank_accounts
  # GET /admin/bank_accounts.json
  def index
    @admin_bank_accounts = BankAccount.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /admin/bank_accounts/1
  # GET /admin/bank_accounts/1.json
  def show
  end

  # GET /admin/bank_accounts/new
  def new
    @admin_bank_account = BankAccount.new
  end

  # GET /admin/bank_accounts/1/edit
  def edit
  end

  # POST /admin/bank_accounts
  # POST /admin/bank_accounts.json
  def create
    @admin_bank_account = BankAccount.new(bank_account_params)
    respond_to do |format|
      if @admin_bank_account.save
        format.html { redirect_to admin_bank_accounts_url, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @admin_bank_account }
      else
        format.html { render :new }
        format.json { render json: @admin_bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/bank_accounts/1
  # PATCH/PUT /admin/bank_accounts/1.json
  def update
    respond_to do |format|
      if @admin_bank_account.update(bank_account_params)
        format.html { redirect_to admin_bank_accounts_url, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_bank_account }
      else
        format.html { render :edit }
        format.json { render json: @admin_bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/bank_accounts/1
  # DELETE /admin/bank_accounts/1.json
  def destroy
    @admin_bank_account.destroy
    respond_to do |format|
      format.html { redirect_to admin_bank_accounts_url, notice: 'Bank account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recalculate_balance
    begin
      @admin_bank_accounts = BankAccount.paginate(:page => params[:page], :per_page => 10)
      bank_account = BankAccount.find(params[:bank_account_id])
      updated_balance = bank_account.recalculate_balance
      success_msg = "#{bank_account.user.fullname} account balance was successfully updated."
      flash[:notice] = success_msg
      
      respond_to do |format|
        format.html { render :index }
        format.json {
          render json: {
            data: number_to_currency_gbp(updated_balance),
            status: :success,
            message: success_msg
          }
        }
      end

    rescue => error
      error_msg = "There was an error: #{error.message}"
      flash[:error] = error_msg
      
      respond_to do |format|
        format.html { render :index }
        format.json { render json: {status: :error, message: error_msg} }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @admin_bank_account = BankAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:user_id, :description, :bank, :sort_code, :account_number, :bank_type, :opening_balance, :balance)
    end
end

app/helpers/admin/bank_accounts_helper.rb
module Admin::BankAccountsHelper
end

app/views/admin/bank_accounts/_form.html.erb
<%= content_for :custom_script do %>
  <script type="text/javascript">
    jQuery(function($){
      // http://digitalbush.com/projects/masked-input-plugin/
      // a - Represents an alpha character (A-Z,a-z)
      // 9 - Represents a numeric character (0-9)
      // * - Represents an alphanumeric character (A-Z,a-z,0-9)
      $("#bank_account_sort_code").mask("**-**-**");
    });
  </script>
<% end %>

<%= render partial: 'partials/form_errors', locals: {data: @admin_bank_account}  %>
<div class="form-group">
  <%= f.label :user_id, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.select :user_id,
      users_for_select,
      {include_blank: '-select here-', selected: @admin_bank_account.user_id},
      {class: 'form-control'}
    %>
  </div>
</div>
<div class="form-group">
  <%= f.label :bank, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :bank, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :sort_code, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :sort_code, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :account_number, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :account_number, class: "form-control", maxlength: "10" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :bank_type, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.select(:bank_type, [
      ['-select here-', ''],
      ['Current', 'Current'],
      ['Savings', 'Savings'],
      ['Merchant', 'Merchant']
      ], {selected: @admin_bank_account.bank_type}, {class: 'form-control'})
    %>
  </div>
</div>
<div class="form-group">
  <%= f.label :opening_balance, class: "col-sm-2 control-label" %>   
  <div class="col-sm-10">
    <div class="input-group">
      <span class="input-group-addon" id="euro-addon1">£</span>
      <%= f.text_field :opening_balance,
        value: "#{@admin_bank_account.opening_balance? ? number_to_currency_field(@admin_bank_account.opening_balance) : '0.00'}",
        class: "form-control",
        aria: {describedby:"euro-addon1"}
      %>
    </div>
  </div>
</div>
<div class="form-group">
  <%= f.label :balance, class: "col-sm-2 control-label" %>   
  <div class="col-sm-10">
    <div class="input-group">
      <span class="input-group-addon" id="euro-addon2">£</span>
      <%= f.text_field :balance,
        value: "#{@admin_bank_account.balance? ? number_to_currency_field(@admin_bank_account.balance) : '0.00'}",
        class: "form-control",
        aria: {describedby:"euro-addon2"}
      %>
    </div>
  </div>
</div>
<div class="form-group">
  <%= f.label :description, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_area :description, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/admin/bank_accounts/edit.html.erb
<div class="page-header">
  <%= link_to admin_bank_accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Editing Bank Account</h1>
  <hr class="colorgraph">
</div>

<%= form_for(@admin_bank_account, {url: admin_bank_account_path(@admin_bank_account), html: { class: "form-horizontal", role: "form" }}) do |field| %>
  <%= render partial: 'form', locals: {f: field} %>
<% end %>

app/views/admin/bank_accounts/index.html.erb
<div class="page-header">
  <%= link_to new_admin_bank_account_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Bank Account
  <% end %>
  <h1>Listing All Bank Accounts</h1>
  <hr class="colorgraph">
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Bank</th>
        <th>Sort code</th>
        <th>Account number</th>
        <th>Type</th>
        <th>Opening-Balance</th>
        <th>Balance</th>
        <th colspan="4" class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
    <%= content_tag_for(:tr, @admin_bank_accounts) do |bank_account| %>
      <td><%= bank_account.bank %></td>
      <td><%= bank_account.sort_code %></td>
      <td><%= bank_account.account_number %></td>
      <td><%= bank_account.bank_type %></td>
      <td><%= number_to_currency_gbp(bank_account.opening_balance) %></td>
      <td id="balance_<%=bank_account.id%>">
        <%= number_to_currency_gbp(bank_account.balance) %>
      </td>
      <td><%= link_to 'Show', admin_bank_account_path(bank_account) %></td>
      <td><%= link_to 'Edit', edit_admin_bank_account_path(bank_account) %></td>
      <td>
        <%= link_to 'Destroy', admin_bank_account_path(bank_account), method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
      <td><%= link_to "Recalculate", admin_bank_account_recalculate_balance_path(bank_account),
        class:"btn btn-sm btn-primary re-calculate",
        data: {bank_account_id: bank_account.id}
        %>
      </td>
    <% end %>
    </tbody>
  </table>
</div>

<div class="pull-right">
  <%= will_paginate @admin_bank_accounts, renderer: BootstrapPagination::Rails %>
</div>

<%= content_for :custom_script do %>
  <script type="text/javascript">
    $(function(){
      var current_bank_account = "<%= params[:bank_account_id] %>";
      $('td').removeClass('bg-primary text-white');
      $('td#balance_'+current_bank_account).addClass('bg-primary text-white');
    });
  </script>
<% end %>

app/views/admin/bank_accounts/new.html.erb
<div class="page-header">
  <%= link_to admin_bank_accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Bank Account</h1>
  <hr class="colorgraph">
</div>

<%= form_for(@admin_bank_account, {url: admin_bank_accounts_path, html: { class: "form-horizontal", role: "form" }}) do |field| %>
  <%= render partial: 'form', locals: {f: field} %>
<% end %>

app/views/admin/bank_accounts/show.html.erb
<div class="page-header">
  <%= link_to admin_bank_accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_admin_bank_account_path(@admin_bank_account), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Bank Account</h1>
  <hr class="colorgraph">
</div>

<dl class="dl-horizontal">
  <dt>Account Holder:</dt>
  <dd><%= @admin_bank_account.user.fullname %></dd>

  <dt>Bank:</dt>
  <dd><%= @admin_bank_account.bank %></dd>

  <dt>Sort code:</dt>
  <dd><%= @admin_bank_account.sort_code %></dd>

  <dt>Account number:</dt>
  <dd><%= @admin_bank_account.account_number %></dd>

  <dt>Type:</dt>
  <dd><%= @admin_bank_account.bank_type %></dd>

  <dt>Opening-Balance:</dt>
  <dd><%= number_to_currency_gbp(@admin_bank_account.opening_balance) %></dd>

  <dt>Balance:</dt>
  <dd><%= number_to_currency_gbp(@admin_bank_account.balance) %></dd>

  <dt>Description:</dt>
  <dd><%= @admin_bank_account.description %></dd>
</dl>