config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    collection do
      match 'setup_totp' => 'users', via: [:get, :post]
      match 'totp_recovery_code' => 'users', via: [:get, :post]
      get 'new_recory_code'
    end
  end

  resources :sessions do
    collection do
      match 'verify_totp_code' => 'sessions', via: [:get, :post]
    end
  end

  resources :password_resets
  resources :dashboard, only: [:index]

  namespace :common_user do
    match 'change_password' => 'abilities#change_password', as: 'change_password', via: [:get, :patch]
    match 'security_settings' => 'abilities#security_settings', as: 'security_settings', via: [:get, :post]
    match 'my_profile' => 'abilities#my_profile', as: 'my_profile', via: [:get, :patch]
  end
  
  namespace :admin do
    resources :users
    resources :bank_accounts do
      get 'recalculate_balance'
    end
    resources :transactions
    resources :transaction_categories
    resources :reports do
      collection do
        get 'filter_report'
        get 'individual_bank_account'
        get ':bank_account/generate_report', action: 'generate_report'
      end
    end
  end

  root to: 'sessions#new'

  match "*path", :to => "application#render_404", via: :all   # renders 404 page when routes not found
  
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController
  before_action :require_login, :allow_admins_only
  before_action :set_admin_transaction, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'

  # GET /admin/transactions
  # GET /admin/transactions.json
  def index
    @admin_transactions = Transaction.order('transaction_date DESC').paginate(:page => params[:page], :per_page => 10)
  end

  # GET /admin/transactions/1
  # GET /admin/transactions/1.json
  def show
  end

  # GET /admin/transactions/new
  def new
    @admin_transaction = Transaction.new
  end

  # GET /admin/transactions/1/edit
  def edit
  end

  # POST /admin/transactions
  # POST /admin/transactions.json
  def create
    @admin_transaction = Transaction.new(admin_transaction_params)

    respond_to do |format|
      if @admin_transaction.save
        format.html { redirect_to admin_transactions_url, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @admin_transaction }
      else
        format.html { render :new }
        format.json { render json: @admin_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/transactions/1
  # PATCH/PUT /admin/transactions/1.json
  def update
    respond_to do |format|
      if @admin_transaction.update(admin_transaction_params)
        format.html { redirect_to admin_transactions_url, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_transaction }
      else
        format.html { render :edit }
        format.json { render json: @admin_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/transactions/1
  # DELETE /admin/transactions/1.json
  def destroy
    @admin_transaction.destroy
    respond_to do |format|
      format.html { redirect_to admin_transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_transaction
      @admin_transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_transaction_params
      params.require(:transaction).permit(:account_id, :transaction_category_id, :credit, :amount, :description, :bank, :transaction_date)
    end
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/views/admin/transactions/_form.html.erb
<%= render partial: 'partials/form_errors', locals: {data: @admin_transaction}  %>

<div class="form-group">
  <%= f.label :bank_account, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.select :account_id,
      user_bank_account_for_select,
      {include_blank: '-select here-', selected: @admin_transaction.account_id},
      {class: 'form-control'}
    %>
  </div>
</div>
<div class="form-group">
  <%= f.label :transaction_category_id, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.select :transaction_category_id,
      transaction_categories_for_select, 
      {include_blank: '-select here-', selected: @admin_transaction.transaction_category_id},
      {class: 'form-control'}
    %>
  </div>
</div>
<div class="form-group">
  <%= f.label :amount, class: "col-sm-2 control-label" %>   
  <div class="col-sm-10">
    <div class="input-group">
      <span class="input-group-addon" id="euro-addon">£</span>
      <%= f.text_field :amount, value: 
        "#{@admin_transaction.amount? ? number_to_currency_field(@admin_transaction.amount) : '0.00'}",
        class: "form-control",
        aria: {describedby:"euro-addon"}
      %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :description, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_area :description, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :transaction_date, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.datetime_select :transaction_date, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/admin/transactions/edit.html.erb
<div class="page-header">
  <%= link_to admin_transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Editing Transaction</h1>
  <hr class="colorgraph">
</div>

<%= form_for(@admin_transaction, {url: admin_transaction_path(@admin_transaction), html: { class: "form-horizontal", role: "form" }}) do |field| %>
  <%= render partial: 'form', locals: {f: field} %>
<% end %>

app/views/admin/transactions/index.html.erb
<div class="page-header">
  <%= link_to new_admin_transaction_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Transaction
  <% end %>
  <h1>Listing All Transactions</h1>
  <hr class="colorgraph">
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Account</th>
        <th>Category</th>
        <th class="text-center">Is Credit?</th>
        <th>Amount</th>
        <th>Transaction Date</th>
        <th colspan="3" class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
    <%= content_tag_for(:tr, @admin_transactions) do |transaction| %>
      <td><%= transaction.user.nil? ? 'Unknown' : transaction.user.fullname %></td>
      <td><%= transaction.transaction_category.nil? ? '-' : transaction.transaction_category.title %></td>
      <td class="text-center">
        <% if transaction.credit %>
          <span class="glyphicon glyphicon-ok"></span>
        <% else %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </td>
      <td><%= transaction.amount %></td>
      <td><%= transaction.transaction_date %></td>
      <td><%= link_to 'Show', admin_transaction_path(transaction) %></td>
      <td><%= link_to 'Edit', edit_admin_transaction_path(transaction) %></td>
      <td><%= link_to 'Destroy', admin_transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tbody>
  </table>
</div>

<div class="pull-right">
  <%= will_paginate @admin_transactions, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/transactions/new.html.erb
<div class="page-header">
  <%= link_to admin_transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Transaction</h1>
  <hr class="colorgraph">
</div>
  
<%= form_for(@admin_transaction, {url: admin_transactions_path, html: { class: "form-horizontal", role: "form" }}) do |field| %>
  <%= render partial: 'form', locals: {f: field} %>
<% end %>

app/views/admin/transactions/show.html.erb
<div class="page-header">
  <%= link_to admin_transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_admin_transaction_path(@admin_transaction), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Transaction</h1>
  <hr class="colorgraph">
</div>

<dl class="dl-horizontal">
  <dt>Account:</dt>
  <dd><%= @admin_transaction.account_id %></dd>

  <dt>Transaction category:</dt>
  <dd><%= @admin_transaction.transaction_category_id %></dd>

  <dt>Credit:</dt>
  <dd><%= @admin_transaction.credit %></dd>

  <dt>Amount:</dt>
  <dd><%= @admin_transaction.amount %></dd>

  <dt>Description:</dt>
  <dd><%= @admin_transaction.description %></dd>

  <dt>Transaction date:</dt>
  <dd><%= @admin_transaction.transaction_date %></dd>
</dl>