config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    collection do
      match 'setup_totp' => 'users', via: [:get, :post]
      match 'totp_recovery_code' => 'users', via: [:get, :post]
      get 'new_recory_code'
    end
  end

  resources :sessions do
    collection do
      match 'verify_totp_code' => 'sessions', via: [:get, :post]
    end
  end

  resources :password_resets
  resources :dashboard, only: [:index]

  namespace :common_user do
    match 'change_password' => 'abilities#change_password', as: 'change_password', via: [:get, :patch]
    match 'security_settings' => 'abilities#security_settings', as: 'security_settings', via: [:get, :post]
    match 'my_profile' => 'abilities#my_profile', as: 'my_profile', via: [:get, :patch]
  end
  
  namespace :admin do
    resources :users
    resources :bank_accounts do
      get 'recalculate_balance'
    end
    resources :transactions
    resources :transaction_categories
    resources :reports do
      collection do
        get 'filter_report'
        get 'individual_bank_account'
        get ':bank_account/generate_report', action: 'generate_report'
      end
    end
  end

  root to: 'sessions#new'

  match "*path", :to => "application#render_404", via: :all   # renders 404 page when routes not found
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :bank_account, dependent: :destroy
  has_many :bank_transactions, through: :bank_account, dependent: :destroy

  validates_presence_of :login, :first_name, :last_name, :email
  validates_format_of :email, :with => /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}\Z/i

  validates_uniqueness_of :login, message: "Username has already registered."
  validates_uniqueness_of :email

  mount_uploader :photo, PhotoUploader

  def is_admin?
    self.user_type_id == 1
  end

  def fullname
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    ApplicationMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.hex
    end while User.exists?(column => self[column])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_login, :allow_admins_only
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = User.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = User.new(user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(user_params)
        format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    # @admin_user.toggle(:activated).save
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :first_name, :last_name, :email, :password, :password_confirmation, :user_type_id, :activated)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :set_user, only: [:edit, :update, :show]
  include ApplicationHelper

  def index
    redirect_to signup_path
  end

  def edit
  end

  def show
    render :edit
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    @user.user_type_id = 1 #admin temporary
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to setup_totp_users_url
    else
      render :new
    end
  end

  def setup_totp
    flash.now.notice = "Please set up your Two-Factor Authentication."
    # Checks if user's activate_totp is already activated, prevent manual page access
    if current_user.activate_totp
      flash[:error] = 'Ooops..! Forbidden page access.'
      redirect_to request.referer || root_path and return
    end

    # Generates new TOTP Secret Key for User every page load
    if request.get?
      current_user.totp_secret = ROTP::Base32.random_base32
      current_user.save
    end

    rotp = RubyOneTimePassword.new(current_user.totp_secret, current_user.email)
    @qr_png = rotp.generate_qr

    if params[:code].present?
      if rotp.verify(params[:code])
        current_user.update_attribute(:totp_recovery_code, encrypt(ROTP::Base32.random_base32))
        redirect_to totp_recovery_code_users_path
      else
        flash.now[:alert] = "Sorry that code didn't match code. Please try again!"
        render :setup_totp
      end
    end
  end

  def new_recory_code
  end

  def totp_recovery_code
    if request.post?
      current_user.update_attribute(:activate_totp, true)
      redirect_to dashboard_index_path, notice: 'Two Factor Authentication was successfully configured.' and return
    end

    flash[:notice] = 'You are one step away, please continue ...'
  end

  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to user_path(@user), notice: 'Profile was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

private  
  def user_params
    params.require(:user).permit(:login, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= render partial: 'partials/form_errors', locals: {data: @admin_user}  %>

<div class="form-group">
  <%= f.label :login, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :login, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :first_name, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :last_name, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :email, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :email, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :password, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.password_field :password, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :user_type_id, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.select(:user_type_id, [['Admin', 1], ['Supervisor', 2]], {selected: @admin_user.user_type_id}, {class: 'form-control'}) %>
  </div>
</div>
<div class="form-group">
  <%= f.label :activated, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.check_box :activated, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <%= link_to admin_users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Editing User</h1>
  <hr class="colorgraph">
</div>

<%= form_for(@admin_user, {url: admin_user_path(@admin_user), html: { class: "form-horizontal", role: "form" }}) do |field| %>
  <%= render partial: 'form', locals: {f: field} %>
<% end %>

app/views/admin/users/index.html.erb
<div class="page-header">
  <%= link_to new_admin_user_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New User
  <% end %>
  <h1>Listing All Users</h1>
  <hr class="colorgraph">
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Login</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>User Type</th>
        <th class="text-center">Activated</th>
        <th colspan="3" class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= content_tag_for(:tr, @admin_users) do |user| %>
        <td><%= user.login %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= identify_user_type(user.user_type_id) %></td>
        <td class="text-center">
          <% if user.activated %>
            <span class="glyphicon glyphicon-ok"></span>
          <% else %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
    </tbody>
  </table>
</div>

<div class="pull-right">
  <%= will_paginate @admin_users, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/users/new.html.erb
<div class="page-header">
  <%= link_to admin_users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New User</h1>
  <hr class="colorgraph">
</div>
  
<%= form_for(@admin_user, {url: admin_users_path, html: { class: "form-horizontal", role: "form" }}) do |field| %>
  <%= render partial: 'form', locals: {f: field} %>
<% end %>

app/views/admin/users/show.html.erb
<div class="page-header">
  <%= link_to admin_users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_admin_user_path(@admin_user), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show User</h1>
  <hr class="colorgraph">
</div>

<dl class="dl-horizontal">
  <dt>Login:</dt>
  <dd><%= @admin_user.login %></dd>

  <dt>First name:</dt>
  <dd><%= @admin_user.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @admin_user.last_name %></dd>

  <dt>Email:</dt>
  <dd><%= @admin_user.email %></dd>

  <dt>User type:</dt>
  <dd><%= identify_user_type(@admin_user.user_type_id) %></dd>

  <dt>Activated:</dt>
  <dd><%= @admin_user.activated %></dd>

</dl>